version: '3.8'

services:
  react:
    build: ./client
    command: npm start
    volumes:
      - ./client/:/usr/src/client/
    ports:
      - '40000:40000'

  nginx:
    image: 'nginx:stable-alpine'
    ports:
      - '40001:80'
    volumes:
      - ./server:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mariadb

  php:
    build: ./server
    links:
      - mariadb
    volumes:
      - ./server:/var/www/html:delegated

  mariadb:
    image: mariadb:10.8.2-rc-focal
    command: --default-storage-engine innodb
    volumes:
      - ./mariadb_data:/var/lib/mysql
    ports:
      - '9906:3306'
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: tweegramm
      MARIADB_USER: admin
      MARIADB_PASSWORD: 1234
      MARIADB_ROOT_PASSWORD: 12345

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_PORT: 3306
    restart: always
    ports:
      - 9907:80
